# Generated by Django 4.1.5 on 2023-02-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("on_boarding_questions", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardingquestion",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
