# Generated by Django 4.1.5 on 2023-02-03 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("on_boarding_questions", "0003_alter_onboardingquestion_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="onboardingquestion",
            name="order",
            field=models.IntegerField(unique=True),
        ),
    ]
